version: "2"
linters:
  default: standard
  enable:
    - misspell
    - usestdlibvars
    - usetesting
formatters:
  enable:
    - goimports
    - golines
  settings:
    golines:
      max-len: 90
      tab-len: 4
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
